global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'expresstix-prometheus-monitoring'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9090']
    metrics_path: '/metrics'

  - job_name: 'expresstix-springboot-monitoring'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]
    metrics_path: '/actuator/prometheus'

  - job_name: 'expresstix-node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:9100' ]

  - job_name: 'expresstix-mysqld-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:9104' ]
    metrics_path: '/metrics'